---

name: Build and Publish Container
permissions:
  contents: read
  packages: write

on:
  release:
    types: [published]
jobs:
  build-and-publish:
    name: Build and Publish Container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@8ca4608ef7f4daeb54f5205b20d0b7cb42f11143
        with:
          pixi-version: v0.55.0
          cache: false
          frozen: true

      - name: Build Container
        run: pixi run -e dev build-container-image